k3s_version: v0.7.0
systemd_dir: /etc/systemd/system
master_ip: "{{ hostvars[groups['masters'][0]].ansible_ens10.ipv4.address }}"

harden_linux_root_password: $5$POPojo.22j48d538$4e4ane2MhsAnvx0KLLIquaQuqKBBbRIFbhri02KuqFD

harden_linux_deploy_user: admin
harden_linux_deploy_user_password: $5$POPojo.22j48d538$4e4ane2MhsAnvx0KLLIquaQuqKBBbRIFbhri02KuqFD
harden_linux_deploy_user_public_keys:
  - /project/ssh_pubkeys/id_rsa.pub

harden_linux_sysctl_settings_user:
  "net.ipv4.ip_forward": 1
  "net.ipv6.conf.default.forwarding": 1
  "net.ipv6.conf.all.forwarding": 1

harden_linux_sshd_settings:
  "^PasswordAuthentication": "PasswordAuthentication no"
  "^PermitRootLogin": "PermitRootLogin no"
  "^PermitTunnel": "PermitTunnel no"
  "^Port ": "Port 22"

harden_linux_ufw_rules:
  - rule: allow
    to_port: "22"
    protocol: tcp

harden_linux_ufw_allow_networks:
  - 10.0.0.0/8

harden_linux_ufw_defaults_user:
  "^DEFAULT_FORWARD_POLICY": 'DEFAULT_FORWARD_POLICY="ACCEPT"'

harden_linux_ufw_logging: on

harden_linux_sshguard_whitelist:
  - 127.0.0.0/8
  - "::1/128"
