version: "3.7"

services:
  controller:
    build: .
    environment:
    - KUBECONFIG=/project/kubeconfigs/$ENV.yaml
    volumes:
    - .:/project
    - ./terraform/.terraformrc:/root/.terraformrc

  dash:
    image: bitnami/kubectl:1.14.3
    environment:
    - KUBECONFIG=/project/kubeconfigs/$ENV.yaml
    volumes:
    - .:/project
    ports:
    - 9443:9443
    command: -n kubernetes-dashboard port-forward svc/kubernetes-dashboard 9443:443 --address=0.0.0.0
