---
- name: Deploy Docker Swarm stacks
  hosts: swarm_nodes
  gather_facts: no
  pre_tasks:
    - name: Decrypt SSH private key.
      delegate_to: localhost
      shell: ansible-vault decrypt /root/.ssh/id_rsa
  tasks:
    - block:
      - synchronize:
          src: ./stacks/
          dest: /stacks/
      - copy:
          src: ./secrets/acme.json
          dest: /acme.json
          force: no
          mode: 0600
          decrypt: yes
      - docker_stack:
          state: present
          name: traefik
          compose:
          - /stacks/traefik.yaml
      - docker_stack:
          state: present
          name: nginx-app
          compose:
          - /stacks/nginx-app.yaml
      - name: Fetch acme.json
        fetch:
          src: /acme.json
          dest: ./secrets/
          flat: yes
      - name: Encrypt acme.json
        delegate_to: localhost
        shell: ansible-vault encrypt ./secrets/acme.json
      always:
        - name: Encrypt private SSH key.
          delegate_to: localhost
          shell: ansible-vault encrypt /root/.ssh/id_rsa
