---
- name: Install python
  hosts: swarm_nodes
  gather_facts: no
  pre_tasks:
    - delegate_to: localhost
      shell: ansible-vault decrypt /root/.ssh/id_rsa
  tasks:
    - raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

- name: Provision nodes and initialize a swarm.
  hosts: swarm_nodes
  roles:
    - provision
  tasks:
    - delegate_to: localhost
      shell: ansible-vault encrypt /root/.ssh/id_rsa
      tags:
        - always
