# Concept for metastore-operator backed by a postgresql database

apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: acid-minimal-cluster
  namespace: default
spec:
  teamId: "acid"
  volume:
    size: 1Gi
  numberOfInstances: 2
  users:
    zalando:  # database owner
    - superuser
    - createdb
    foo_user: []  # role for application foo
  databases:
    foo: zalando  # dbname: owner
  postgresql:
    version: "11"

---

apiVersion: metastore.flexp.live/v1alpha1
kind: Metastore
metadata:
  name: default
  namespace: default
spec:
  dbConnection:
    secretName: ""
  thiftServer:
    image: registry.flexp.live/hive:3.1.2
    conf: {}
    configMap: {}
    service:
      type: ClusterIP
      port: 9083
#
# apiVersion: metastore.flexp.live/v1alpha1
# kind: Database
# metadata:
#   name: default
#   namespace: default
# spec: {}
#
# ---
#
# apiVersion: metastore.flexp.live/v1alpha1
# kind: Table
# metadata:
#   name: default
#   namespace: default
# spec: {}
