---
- name: Set hostname.
  hostname:
    name: "{{ node_hostname }}"

- name: Add hostname entries to hosts file (localhost)
  lineinfile:
    dest: /etc/hosts
    regexp: "^127.0.0.1"
    line: "127.0.0.1 localhost {{ node_hostname }}"
    state: present

- name: Set locale.
  command: "/usr/sbin/update-locale LANG={{ locale }} LC_ALL={{ locale }}"

- name: Set local time.
  command: "/bin/cp --remove-destination /usr/share/zoneinfo/{{ timezone }} /etc/localtime"

- name: Set timezone.
  template:
    src: etc/timezone
    dest: /etc/timezone
  notify: update tzdata
