version: "3.7"

services:
  controller:
    build: .
    volumes:
    - .:/project
    - ./terraform/.terraformrc:/root/.terraformrc

  k6s:
    image: loadimpact/k6
    working_dir: /k6s
    volumes:
    - ./k6s:/k6s
