# nameOverride: ""
# fullNameOverride: ""
hcloudToken:
  createSecret: true
  token: ""
  # secretKeyRef is used only if create is set to false
  secretKeyRef:
    name: ""
    key: ""

CSIDriverName: csi.hetzner.cloud

registrar:
  image: quay.io/k8scsi/csi-node-driver-registrar
  imageTag: v1.1.0
  imagePullPolicy: Always

driver:
  image: hetznercloud/hcloud-csi-driver
  imageTag: 1.1.4
  imagePullPolicy: Always

provisioner:
  image: quay.io/k8scsi/csi-provisioner
  imageTag: v1.2.1
  imagePullPolicy: Always

attacher:
  image: quay.io/k8scsi/csi-attacher
  imageTag: v1.1.1
  imagePullPolicy: Always

hostPathVolumes:
  kubeletDir: /var/lib/kubelet
  pluginDir: /var/lib/kubelet/plugins/csi.hetzner.cloud/
  registrationDir: /var/lib/kubelet/plugins_registry/
  deviceDir: /dev

storageClass:
  name: hcloud-volumes
  isDefaultClass: true
