debug = false
logLevel = "INFO"
defaultEntryPoints = ["https", "http"]

[traefikLog]
format = "json"

[accessLog]
format = "json"

[entryPoints]
[entryPoints.dashboard]
address = ":8080"

[entryPoints.http]
address = ":80"
[entryPoints.http.redirect]
entryPoint = "https"
[entryPoints.https]
address = ":443"
[entryPoints.https.tls]

[api]
entrypoint="dashboard"

[docker]
endpoint = "unix:///var/run/docker.sock"
exposedByDefault = false
swarmMode = true
network = "web"

[acme]
email = "i@pxl.fi"
storage = "acme.json"
# caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
entryPoint = "https"
acmeLogging = true
onHostRule = true

[acme.httpChallenge]
entryPoint = "http"
