apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClass.name }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "hcloud-csi.chart" . }}
    app: {{ template "hcloud-csi.name" . }}
  annotations:
    storageclass.kubernetes.io/is-default-class: {{ .Values.storageClass.isDefaultClass | quote }}
provisioner: {{ .Values.CSIDriverName }}
volumeBindingMode: WaitForFirstConsumer
