- hosts: harden_linux:k3s_cluster
  gather_facts: no
  tasks:
    - name: Wait for node to become available via SSH
      wait_for_connection:
        timeout: 60
    - name: Wait for automatic system updates
      raw: systemd-run --property="After=apt-daily.service apt-daily-upgrade.service" --wait /bin/true
  tags:
    - linux

- name: Harden Linux installation for improved security
  hosts: harden_linux
  roles:
    - harden-linux
  tags:
    - linux

- name: Install k3s on master node
  hosts: masters
  roles:
    - role: k3s-master
  tags:
    - k3s
    - k3s-master

- name: Install k3s on worker nodes
  hosts: nodes
  roles:
    - role: k3s-node
  tags:
    - k3s
    - k3s-node
