repositories:
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com
- name: incubator
  url: https://kubernetes-charts-incubator.storage.googleapis.com
- name: jetstack
  url: https://charts.jetstack.io
- name: elastic
  url: https://helm.elastic.co
