helmDefaults:
  wait: true
  force: true
  recreatePods: false
  tillerless: true
  tillerNamespace: kube-system

releases:

- name: elasticsearch
  installed: true
  namespace: logging
  labels:
    group: efk
    app: elasticsearch
  chart: elastic/elasticsearch
  version: 7.3.0
  values:
  - replicas: 1
    antiAffinity: soft
    esJavaOpts: -Xmx512m -Xms512m
    resources:
      requests:
        cpu: 100m
        memory: 1024Mi
      limits:
        cpu: 1000m
        memory: 1024Mi
    volumeClaimTemplate:
      accessModes: ["ReadWriteOnce"]
      storageClassName: hcloud-volumes
      resources:
        requests:
          storage: 20Gi

- name: fluent-bit
  installed: true
  namespace: logging
  labels:
    group: efk
    app: fluent-bit
  chart: stable/fluent-bit
  version: 2.4.4
  values:
  - metrics:
      enabled: true
    serviceMonitor:
      enabled: false
    trackOffsets: false
    filter:
      mergeJSONLog: true
      mergeLogKey: data
    input:
      tail:
        memBufLimit: 5MB
        parser: cri-containerd
        path: /var/log/containers/*.log
    parsers:
      enabled: true
      regex:
      - name: cri-containerd
        regex: '^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<log>.*)$'
        timeFormat: '%Y-%m-%dT%H:%M:%S.%L%z'
    backend:
      type: es
      es:
        host: elasticsearch-master
        port: 9200

- name: kibana-ingress-auth
  installed: true
  namespace: logging
  labels:
    group: efk
    app: kibana-ingress-auth
  chart: incubator/raw
  values:
  - resources:
    - apiVersion: v1
      kind: Secret
      metadata:
        name: kibana-ingress-auth
      type: Opaque
      stringData:
        auth: "{{ requiredEnv "KIBANA_AUTH" }}"

- name: kibana
  installed: true
  namespace: logging
  labels:
    group: efk
    app: kibana
  chart: elastic/kibana
  version: 7.3.0
  values:
  - elasticsearchHosts: http://elasticsearch-master:9200
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        kubernetes.io/tls-acme: "true"
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        nginx.ingress.kubernetes.io/auth-type: basic
        nginx.ingress.kubernetes.io/auth-secret: kibana-ingress-auth
        nginx.ingress.kubernetes.io/auth-realm: Authentication Required
      hosts:
      - kibana.{{ .Values.applicationDomainZone }}
      tls:
      - secretName: kibana-ingress-tls
        hosts:
        - kibana.{{ .Values.applicationDomainZone }}
