helmDefaults:
  wait: true
  force: true
  recreatePods: false
  tillerless: true
  tillerNamespace: kube-system

releases:

- name: forms-app
  installed: true
  namespace: default
  labels:
    app: forms-app
  chart: ../charts/nginx-react
  values:
  - replicaCount: 5
    image:
      repository: ilyasotkov/forms-app
      tag: 0.3.2
      pullPolicy: IfNotPresent
    serviceType: ClusterIP
    servicePort: 80
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        kubernetes.io/tls-acme: "true"
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      hosts:
      - forms-app.{{ .Values.applicationDomainZone }}
      tls:
      - secretName: forms-app-tls
        hosts:
        - forms-app.{{ .Values.applicationDomainZone }}
