helmDefaults:
  wait: true
  force: true
  recreatePods: false
  tillerless: true
  tillerNamespace: kube-system

releases:

- name: hcloud-csi
  installed: true
  namespace: hcloud-csi
  labels:
    app: hcloud-csi
  chart: ../charts/hcloud-csi
  values:
  - hcloudToken:
      token: {{ requiredEnv "HCLOUD_TOKEN" }}
    hostPathVolumes:
      kubeletDir: /var/lib/kubelet
      pluginDir: /var/lib/kubelet/plugins/csi.hetzner.cloud
      registrationDir: /var/lib/kubelet/plugins_registry
      deviceDir: /dev
