helmDefaults:
  wait: true
  force: true
  recreatePods: false
  tillerless: true
  tillerNamespace: kube-system

releases:

- name: istio-init
  installed: true
  namespace: istio-system
  labels:
    group: istio
    app: istio-init
  chart: istio.io/istio-init
  values: []
  hooks:
  - events: ["postsync"]
    command: "sleep"
    args: ["30"]

- name: istio
  installed: true
  namespace: istio-system
  labels:
    group: istio
    app: istio
  chart: istio.io/istio
  values:
  - gateways:
      istio-ingressgateway:
        sds:
          enabled: true
        ports:
        - port: 80
          targetPort: 80
          name: http2
        - port: 443
          targetPort: 443
          name: https
  hooks:
  - events: ["postsync"]
    command: ../../scripts/knative-install.sh
