helmDefaults:
  wait: true
  force: true
  recreatePods: false
  tillerless: true
  tillerNamespace: kube-system

releases:

- name: dash
  installed: true
  namespace: kube-system
  labels:
    app: dash
  chart: incubator/raw
  hooks:
  - events: ["presync"]
    command: "k3s"
    args:
    - kubectl
    - apply
    - -f
    - https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-beta3/aio/deploy/recommended.yaml
  values:
  - resources:
    - apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: dash-user
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: dash-user
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: cluster-admin
      subjects:
      - kind: ServiceAccount
        name: dash-user
        namespace: kube-system

- name: metrics-server
  installed: true
  namespace: kube-system
  labels:
    app: metrics-server
  chart: stable/metrics-server
  version: 2.8.2
  values: []
