apiVersion: storage.k8s.io/v1beta1
kind: CSIDriver
metadata:
  name: {{ .Values.CSIDriverName }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "hcloud-csi.chart" . }}
    app: {{ template "hcloud-csi.name" . }}
spec:
  attachRequired: true
  podInfoOnMount: true
