{{- if .Values.hcloudToken.createSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "hcloud-csi.fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "hcloud-csi.chart" . }}
    app: {{ template "hcloud-csi.name" . }}
stringData:
  token: {{ .Values.hcloudToken.token }}
{{- end -}}
