version: "2.6"

tasks:

  cluster:
    deps: [tfapply]
    dir: ./ansible
    vars:
      ansible_inventory_path: /tmp/inventory.json
    cmds:
      - ./inventory.py > {{ .ansible_inventory_path }}
      - ansible-playbook provision.yml --inventory {{ .ansible_inventory_path }}

  tfapply:
    deps: [tfinit]
    dir: ./terraform
    cmds:
      - terraform apply -auto-approve

  tfplan:
    deps: [tfinit]
    dir: ./terraform
    cmds:
      - terraform plan

  tfplandestroy:
    deps: [tfinit]
    dir: ./terraform
    cmds:
      - terraform plan -destroy

  tfdestroy:
    deps: [tfinit]
    dir: ./terraform
    cmds:
      - terraform destroy

  tfinit:
    dir: ./terraform
    cmds:
      - terraform init
    sources:
      - main.tf
    generates:
      - .terraform/plugins/linux_amd64/lock.json
    method: checksum
