apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "hcloud-csi.fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "hcloud-csi.chart" . }}
    app: {{ template "hcloud-csi.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "hcloud-csi.fullname" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "hcloud-csi.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
