apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "hcloud-csi.fullname" . }}-controller
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "hcloud-csi.chart" . }}
    app: {{ template "hcloud-csi.name" . }}
spec:
  serviceName: {{ template "hcloud-csi.fullname" . }}-controller
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "hcloud-csi.name" . }}-controller
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "hcloud-csi.name" . }}-controller
        release: {{ .Release.Name }}
    spec:
      serviceAccount: {{ template "hcloud-csi.fullname" . }}
      containers:
        - name: csi-attacher
          image: {{ .Values.csiAttacher.image }}:{{ .Values.csiAttacher.imageTag }}
          imagePullPolicy: {{ .Values.csiAttacher.imagePullPolicy }}
          args:
            - --csi-address=/var/lib/csi/sockets/pluginproxy/csi.sock
            - --v=5
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
        - name: csi-provisioner
          image: {{ .Values.csiProvisioner.image }}:{{ .Values.csiProvisioner.imageTag }}
          args:
            - --provisioner={{ .Values.CSIDriverName }}
            - --csi-address=/var/lib/csi/sockets/pluginproxy/csi.sock
            - --feature-gates=Topology=true
            - --v=5
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
        - name: hcloud-csi-driver
          image: {{ .Values.csiDriver.image }}:{{ .Values.csiDriver.imageTag }}
          imagePullPolicy: {{ .Values.csiDriver.imagePullPolicy }}
          env:
            - name: CSI_ENDPOINT
              value: unix:///var/lib/csi/sockets/pluginproxy/csi.sock
            - name: HCLOUD_TOKEN
              valueFrom:
                secretKeyRef:
{{- if .Values.hcloudToken.createSecret }}
                  name: {{ template "hcloud-csi.fullname" . }}
                  key: token
{{- else }}
{{ toYaml .Values.hcloudToken.secretKeyRef | indent 18 }}
{{- end }}
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
      volumes:
        - name: socket-dir
          emptyDir: {}
