version: "3"

services:
  nginx:
    image: nginx:1.17.1-alpine
    ports:
    - 8080:8080
    restart: always
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
  flask:
    image: ${REGISTRY_URL:?err}/flask-app:1.0.0
    build: .
    # ports:
    # - "5000:5000"
    # volumes:
    # - .:/app
    # environment:
    # - FLASK_APP=server.py
    # working_dir: /project/app
    # command: python3 server.py
    restart: always
  db:
    image: mongo
