- name: Reload ufw
  ufw:
    state: reloaded

- name: Restart ssh
  service:
    name: ssh
    state: restarted

- name: Restart ntpd
  service:
    name: "{{ harden_linux_ntp }}"
    state: restarted
