wireguard_cert_directory: "{{ '~/wireguard/certs' | expanduser }}"
wireguard_cert_owner: "root"
wireguard_cert_group: "root"
wireguard_remote_directory: "/etc/wireguard"
wireguard_port: "51820"
wireguard_interface: "wg0"
