helmfiles:

###############################################################################
# CLOUD PLATFORM
###############################################################################

# Helm repositories
- path: ./helmfiles/_repositories.yaml

# Hetzner Cloud integrations
- path: ./helmfiles/hcloud.yaml

# Enable LoadBalancer type of service for ingress controller
- path: ./helmfiles/metallb.yaml
  values:
  - masterIpAddress: {{ .Values.masterIpAddress }}

# Install NGINX ingress controller, cert-manager, external-dns
- path: ./helmfiles/ingress.yaml
  values:
  - applicationDomainZone: {{ .Values.applicationDomainZone }}

# Install monitoring stack
- path: ./helmfiles/monitoring.yaml

# Install logging stack
- path: ./helmfiles/efk.yaml
  values:
  - applicationDomainZone: {{ .Values.applicationDomainZone }}


###############################################################################
# APPLICATIONS
###############################################################################

- path: ./helmfiles/forms-app.yaml
  values:
  - applicationDomainZone: {{ .Values.applicationDomainZone }}
