helmfiles:

# Update Helm repos
- path: ./helmfiles/_repositories.yaml

# Hetzner Cloud integrations
# Disabled due to https://github.com/hetznercloud/csi-driver/issues/46
- path: ./helmfiles/hcloud.yaml

# Enable LoadBalancer type of service for ingress controller
- path: ./helmfiles/metallb.yaml
  values:
  - masterIpAddress: {{ .Values.masterIpAddress }}

- path: ./helmfiles/ingress.yaml
  values:
  - applicationDomainZone: {{ .Values.applicationDomainZone }}

# Install monitoring stack
- path: ./helmfiles/monitoring.yaml

# Install logging stack
- path: ./helmfiles/efk.yaml
  values:
  - applicationDomainZone: {{ .Values.applicationDomainZone }}


###############################################################################
# APPLICATIONS
###############################################################################

- path: ./helmfiles/forms-app.yaml
  values:
  - applicationDomainZone: {{ .Values.applicationDomainZone }}
