version: "3.7"

networks:
  web:
    external: true
  internal:
    external: false

services:
  nginx:
    image: nginx:latest
    restart: always
    networks:
      - web
      - internal
    deploy:
      labels:
        traefik.enable: "true"
        traefik.docker.network: web
        traefik.port: "80"
        traefik.frontend.rule: Host:app.flexp.xyz
        traefik.protocol: http
