version: "3.7"

networks:
  internal: {}
  traefik:
    external: true

configs:
  nginx_config:
    name: flask-app-nginx-config-${FLASK_APP_NGINX_CONFIG_CHECKSUM}
    file: ./configs/flask-app/nginx.conf

services:
  nginx:
    image: nginx:1.17.1-alpine
    ports:
    - "8888:8888"
    configs:
    - source: nginx_config
      target: /etc/nginx/nginx.conf
    deploy:
      labels:
        traefik.enable: "true"
        traefik.docker.network: traefik
        traefik.port: "8888"
        traefik.frontend.rule: Host:api.flexp.xyz
        traefik.protocol: http
    networks:
    - internal
    - traefik
  flask:
    image: r.flexp.xyz/flask-app:latest
    networks:
    - internal
  db:
    image: mongo
    networks:
    - internal
