- hosts: k3s_cluster
  gather_facts: False
  tasks:
    - name: install python 2
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
  tags:
    - linux

- hosts: k3s_cluster
  tasks:
    - debug:
        var: leader_manager_advertise_addr
  tags:
    - debug

- name: Run miscellaneous tasks for Linux
  hosts: k3s_cluster
  tasks:
  - name: Set hostname
    hostname:
      name: "{{ ansible_host.split('.')[0] }}"
  tags:
    - linux

- name: Harden Linux installation for improved security
  hosts: harden_linux
  roles:
    - githubixx-ansible-role-harden-linux
  tags:
    - linux

- name: WireGuard VPN
  hosts: vpn
  roles:
    - role: githubixx-ansible-role-wireguard
      when: ansible_user != "root"
  tags:
    - wg

- name: Install k3s on master node
  hosts: master
  roles:
    - role: k3s-master
      when: ansible_user != "root"
  tags:
    - k3s

- name: Install k3s on worker nodes
  hosts: node
  roles:
    - role: k3s-node
      when: ansible_user != "root"
  tags:
    - k3s
