- name: Fetch kubeconfig to local machine
  hosts: kube-master[0]
  tasks:
  - name: Fetch kubeconfig
    fetch:
      src: /etc/kubernetes/admin.conf
      dest: "{{ fetch_kubeconfig_path }}"
      flat: yes

  - name: Update kubernetes endpoint in local kubeconfig
    delegate_to: localhost
    connection: local
    replace:
      path: "{{ fetch_kubeconfig_path }}"
      regexp: "https://{{ hostvars[groups['kube-master'][0]].ip }}:6443"
      replace: "https://{{ hostvars[groups['kube-master'][0]].ansible_eth0.ipv4.address }}:6443"

  - name: Allow communication to Kubernetes master
    ufw:
      rule: allow
      from_ip: "{{ kube_api_allowed_sources }}"
      to_ip: any
      from_port: ""
      to_port: 6443
      protocol: any
      log: false
