ungrouped:
  hosts:
    localhost:
      ansible_connection: local
all:
  hosts:
    master1:
      ansible_host: linode-swarm-node-1.flexp.xyz
      wireguard_endpoint: linode-swarm-node-1.flexp.xyz
      wireguard_address: 10.8.0.101/24
      docker_swarm_role: leader_manager
    worker1:
      ansible_host: linode-swarm-node-2.flexp.xyz
      wireguard_endpoint: linode-swarm-node-2.flexp.xyz
      wireguard_address: 10.8.0.102/24
    worker2:
      ansible_host: linode-swarm-node-3.flexp.xyz
      wireguard_endpoint: linode-swarm-node-3.flexp.xyz
      wireguard_address: 10.8.0.103/24
nodes:
  vars:
    node_hosting_provider: linode
    # Change the below after running `ansible-playbook provision.yml` for the first time
    ansible_user: root
    # ansible_user: deploy
    # ansible_become: yes
    ansible_ssh_private_key_file: /linode-swarm/.ssh/id_rsa
    leader_manager_advertise_addr: "{{ hostvars.master1.ansible_wg0.ipv4.address }}"
  children:
    managers:
      vars:
        docker_swarm_role: managers
      hosts:
        master1: {}
    workers:
      vars:
        docker_swarm_role: worker
      hosts:
        worker1: {}
        worker2: {}
vpn:
  hosts:
    master1: {}
    worker1: {}
    worker2: {}
harden_linux:
  hosts:
    master1: {}
    worker1: {}
    worker2: {}
