- name: Download k3s binary
  get_url:
    url: https://github.com/rancher/k3s/releases/download/{{ k3s_version }}/k3s
    dest: /usr/local/bin/k3s
    owner: root
    group: root
    mode: 0700

- name: Create k3s-worker.service file
  register: k3s_service
  template:
    src: k3s-worker.service.j2
    dest: "{{ systemd_dir }}/k3s-worker.service"
    owner: root
    group: root
    mode: 0644

- name: Enable and restart k3s-worker.service
  systemd:
    name: k3s-worker
    daemon_reload: yes
    state: restarted
    enabled: yes
