version: "3.7"

configs:
  traefik_config:
    name: traefik-config-${TRAEFIK_CONFIG_CHECKSUM}
    file: ./configs/traefik/config.toml

networks:
  traefik:
    name: traefik
    external: false

services:
  traefik:
    container_name: traefik
    image: traefik:1.7.12
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /acme.json:/acme.json
    configs:
      - source: traefik_config
        target: /etc/traefik/traefik.toml
    networks:
      - traefik
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
      - target: 8080
        published: 8080
        mode: host
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 5s
