variables:
  hcloud_token: "{{ env `HCLOUD_TOKEN` }}"

builders:
- type: hcloud
  token: "{{ user `hcloud_token` }}"
  image: ubuntu-18.04
  location: hel1
  server_type: cx11
  ssh_username: root

provisioners:
- type: ansible
  host_alias: k3s-packer
  playbook_file: ./provision.yml
  extra_arguments:
  - --skip-tags
  - packer-ignore
  - --extra-vars
  - ansible_python_interpreter=/usr/bin/python python_version=2
  groups:
  - all
  - harden_linux
  - nodes
