helmDefaults:
  wait: true
  force: true
  recreatePods: false
  tillerless: true
  tillerNamespace: kube-system

releases:

- name: local-path-provisioner
  installed: true
  namespace: local-path-storage
  labels:
    app: local-path-provisioner
  chart: ../charts/local-path-provisioner
  values:
  - fullnameOverride: local-path-provisioner
