- local_action: stat path=../secrets/acme.json
  register: acme_file_exists_locally

- when: not acme_file_exists_locally.stat.exists
  file:
    state: touch
    path: /acme.json
    mode: 0600

- when: acme_file_exists_locally.stat.exists
  copy:
    src: ../secrets/acme.json
    dest: /acme.json
    force: no
    mode: 0600
    decrypt: yes

- name: Check if acme.json already exists on server
  stat:
    path: /acme.json
  register: acme_json_exists

- name: Fetch acme.json
  when: acme_json_exists.stat.exists
  fetch:
    src: /acme.json
    dest: ../secrets/
    flat: yes
