- name: Copy files to leader manager node
  synchronize:
    src: "{{ stack_path }}/"
    dest: /stacks/
    delete: yes
- import_tasks: fetch-acme.yml
  tags: ["acme"]
- include_tasks: traefik.yml
  tags: ["traefik"]
- import_tasks: registry.yml
  tags: ["registry"]
- import_tasks: nginx-app.yml
  tags: ["nginx-app"]
# - import_tasks: flask-app.yml
